<tr>
    <td><a class="btn btn-small btn-info" href='/bug/edit/id/<?php echo $this->id; ?>'><i class="icon-edit icon-white"></i></a>&nbsp;&nbsp;
        <a class="btn btn-small btn-danger" href='/bug/delete/id/<?php echo $this->id; ?>'><i class="icon-trash icon-white"></i></a></td>
    <td><?php echo date('m/d/y', $this->date); ?></td>
    <td><?php echo $this->priority; ?></td>
    <td><?php echo $this->status; ?></td>
    <td><?php echo $this->url; ?></td>
    <td><?php echo $this->author; ?></td>
    <td><?php echo $this->description; ?></td>
</tr>
