<?php
if ($this->pageCount) {
// you need to add each of the request parameters to url
    $params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
// remove the system parameters
    unset($params['module']);
    unset($params['controller']);
    unset($params['action']);
    ?>
    <div class="pagination">
        <ul>
        <!-- Previous page link -->
           <?php if (isset($this->previous)) { ?>
            <li><a href="<?php echo $this->url(array_merge(
                               $params, array('page' => $this->previous)));
               ?>">
                &lt; Previous
            </a></li>
        <?php } else { ?>
            <li class="disabled"><a href="#">&lt; Previous</a></li>
        <?php } ?>
        <!-- Numbered page links -->
           <?php foreach ($this->pagesInRange as $page) { ?>
               <?php if ($page != $this->current) { ?>
        <li><a href="<?php echo $this->url(array_merge($params, array('page' => $page)));
                   ?>">
                <?php echo $page; ?>
                </a></li>
            <?php } else { ?>
                <li class="active"><a href="#"><?php echo $page; ?></a></li>
            <?php }
        } ?>
        <!-- Next page link -->
    <?php if (isset($this->next)) { ?>
        <li><a href="<?php echo $this->url(
                array_merge($params, array('page' => $this->next)));
        ?>">
                Next &gt;
            </a></li>
    <?php } else { ?>
            <li class="disabled"><a href="#">Next &gt;</a></li>
    <?php } ?>
        </ul>
    </div>
<?php } ?>
